name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
 
    - name: dotnet build
      run: dotnet build TodoApi.sln -c Release

    - name: dotnet test
      run: dotnet test TodoApi.sln -c Release --no-build
    
    #Run Snyk Security Scan and fail build on high or critical severity vulnerabilities
    - name: Snyk Security Scan
      uses: snyk/actions/dotnet@master
      with:
        args: 
          --severity-threshold=high
          --all-projects
          --sarif-file-output=snyk.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif